- hosts: all
  tasks:
    - include_vars: Ubuntu.yml
      when: ansible_facts.os_family == "Debian"
    
    - include_vars: Fedora.yml
      when: ansible_facts.os_family == "RedHat"
    
    - package:
        name: "{{ pkg }}"
        state: present

    - copy:
        src: index.html
        dest: /var/www/html/index.html

    - service:
        name: "{{ pkg }}"
        state: started

      
