- hosts: all
  vars_files:
    "{{ ansible_facts.distribution }}.yml"
  tasks:
    - name: Installing Packages
      package:
        name: "{{ pkg }}"
        state: present

    - name: Copying Webapage
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Starting service
      service:
        name: "{{ pkg }}"
        state: started

      
