- name: Installing docker and kubernetes dependencies on Master & Worker Nodes
  hosts: master, workers
  tasks:
    - name: Installing docker
      yum:
        name: docker
        state: present

    - name: Yum repo for K8s
      yum_repository:
        name: kubernetes
        description: kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude: 
          - kubelet
          - kubeadm
          - kubectl
    - name: Installing kubeadm, kubelet and kubectl"
      yum:
        name: 
          - kubeadm
          - kubelet
          - kubectl 
        state: present
        disable_excludes: kubernetes
    
    - name: Starting docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: configuring daemon.json
      copy:
        dest: "/etc/docker/daemon.json"
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"]
          }

    - name: Restarting docker services
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Enabling kubelet
      service:
        name: kubelet
        state: started
        enabled: yes

- name: Configuring Master 
  hosts: master
  tasks:
    - name: Pulling essential images
      shell: "kubeadm config images pull"

    - name: Installing iproute-tc
      package:
        name: iproute-tc
        state: present
    
    - name: Setting bridge-nf-call-iptables to 1
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF
    
    - name: Restarting bridge settings
      shell: "sysctl --system"

    - name: Initializing the Master Node
      shell: "kubeadm init --pod-network-cidr=10.244.0.0/16  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
      ignore_errors: yes
      register: init 
    
    - name: Creating .kube directory
      file:
        path: "/root/.kube"
        state: directory

    - name: Copying admin.conf
      shell: "cp -i /etc/kubernetes/admin.conf /root/.kube/config"
        
    - name: Changing owner permission
      shell: "sudo chown $(id -u):$(id -g) /root/.kube/config"

    - name: Generating token
      shell: "kubeadm token create  --print-join-command"
      register: token

    - name: add variables to dummy host
      add_host:
        name: "variable_holder"
        shared_variable:  "{{ token }}"

- name: Configuring Worker
  hosts: workers
  vars:
   shared_variable: "{{ hostvars['variable_holder']['shared_variable'] }}"
  tasks:
    - name: Installing iproute-tc
      package:
        name: iproute-tc
        state: present

    - name: Setting bridge-nf-call-iptables to 1
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF

    - name: Restarting bridge settings
      shell: "sysctl --system"
    - name: Printing token
      debug:
        var: shared_variable.stdout   
    
    - name: Joining Master
      shell: "{{ shared_variable.stdout }}"
      register: joined
- name: Configuring flannel
  hosts: master
  tasks:
    - name: Configuring flannel
      shell: kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

